//using System;
//using System.IO;
//using System.Reflection;

//using DoofesZeug.Attributes;
//using DoofesZeug.Extensions;
//using DoofesZeug.Models;


//using static System.Console;



//namespace DoofesZeug.Checks
//{
//    public static class CheckNamespaces
//    {
//        private static readonly string DIV = new string('-', 80);

//        private static readonly string SOURCE = @"O:\DoofesZeug\DoofesZeug.Library\Src";

//        //-------------------------------------------------------------------------------------------------------------------------------------------------------------------------


//        public static bool Execute()
//        {
//            bool bSuccess = true;
//            Type tEntityBase = typeof(EntityBase);

//            Assembly assembly = tEntityBase.Assembly;

//            Out.WriteLineAsync($"{assembly.FullName}");

//            foreach( Type type in assembly.ExportedTypes )
//            {
//                if( type.GetCustomAttribute(typeof(GeneratedAttribute)) != null )
//                {
//                    // We skip the autogenerated code.
//                    continue;
//                }

//                string strName = type.Name;
//                string strNamespace = type.Namespace;

//                Out.WriteLineAsync(DIV);
//                Out.WriteLineAsync($"{strName}");
//                Out.WriteLineAsync($"{strNamespace}");

//                if( strNamespace.IsEmpty() == true )
//                {
//                    Error.WriteLineAsync($"{type.FullName} have no namespace!");
//                    bSuccess = false;
//                }

//                if( strNamespace.StartsWith("DoofesZeug.") == false )
//                {
//                    Error.WriteLineAsync($"{type.FullName} have not the right namespace!");
//                    bSuccess = false;
//                }

//                strNamespace = strNamespace [11..];
//                int iIndex = strName.IndexOf("`");
//                if( iIndex > 0 )
//                {
//                    strName = strName.Substring(0, iIndex);
//                }

//                string strSourceFile = $"{SOURCE}\\{ strNamespace.Replace('.', '\\') }\\{strName}.cs";
//                Out.WriteLineAsync(strSourceFile);

//                if( File.Exists(strSourceFile) == false )
//                {
//                    Error.WriteLineAsync($"{type.FullName} is not in the right folder!");
//                }
//            }

//            //bSuccess = false;
//            return bSuccess;
//        }
//    }
//}
